require:
  - rubocop-discourse

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
Style/Documentation:
  Enabled: false
Discourse:
  Enabled: true
