inherit_from: .rubocop_todo.yml

require:
  - rubocop-discourse

AllCops:
  NewCops: enable
  Exclude:
    - 'db/migrate/20220505113156_create_active_storage_tables.active_storage.rb'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'vendor/**/*'
Style/Documentation:
  Enabled: false
Discourse:
  Enabled: true
